webtalk_init -webtalk_dir D:\\Project\\PWM_2018\\project_1.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2023-03-02 18:51:38" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fdqd1sdra8se7qt115lsc2h5u" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-12500" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.851 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1677749454014" -context "sdk\\\\application/1677749454014"
webtalk_add_data -client sdk -key hwid -value "1677735120625" -context "sdk\\\\application/1677749454014"
webtalk_add_data -client sdk -key bspid -value "1677735210258" -context "sdk\\\\application/1677749454014"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1677749454014"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1677749454014"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1677749454014"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1677749454014"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1677749454014"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1677749454014"
webtalk_add_data -client sdk -key projSize -value "593.6171875" -context "sdk\\\\application/1677749454014"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1677754298330"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1677754298330"
webtalk_add_data -client sdk -key BootgenCount -value "1" -context "sdk\\\\bsp/1677754298330"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1677754298330"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1677754298330"
webtalk_add_data -client sdk -key FlashCount -value "1" -context "sdk\\\\bsp/1677754298330"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1677754298330"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1677754298330"
webtalk_transmit -clientid 3082947290 -regid "" -xml D:\\Project\\PWM_2018\\project_1.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\Project\\PWM_2018\\project_1.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\Project\\PWM_2018\\project_1.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
