# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/PWM/PWM.bd
# Block Designs: The module: 'PWM' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/PWM/ip/PWM_processing_system7_0_0/PWM_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_processing_system7_0_0 || ORIG_REF_NAME==PWM_processing_system7_0_0} -quiet] -quiet

# IP: bd/PWM/ip/PWM_PWM_module_0_0/PWM_PWM_module_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_PWM_module_0_0 || ORIG_REF_NAME==PWM_PWM_module_0_0} -quiet] -quiet

# IP: bd/PWM/ip/PWM_rst_ps7_0_200M_1/PWM_rst_ps7_0_200M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_rst_ps7_0_200M_1 || ORIG_REF_NAME==PWM_rst_ps7_0_200M_1} -quiet] -quiet

# IP: bd/PWM/ip/PWM_key_debounce_0_3/PWM_key_debounce_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_key_debounce_0_3 || ORIG_REF_NAME==PWM_key_debounce_0_3} -quiet] -quiet

# IP: bd/PWM/ip/PWM_ps7_0_axi_periph_0/PWM_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_ps7_0_axi_periph_0 || ORIG_REF_NAME==PWM_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/PWM/ip/PWM_COM_IP_0_1/PWM_COM_IP_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_COM_IP_0_1 || ORIG_REF_NAME==PWM_COM_IP_0_1} -quiet] -quiet

# IP: bd/PWM/ip/PWM_auto_pc_0/PWM_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_auto_pc_0 || ORIG_REF_NAME==PWM_auto_pc_0} -quiet] -quiet

# XDC: d:/Project/Wireless_Charge_PWM/PWM/PWM.gen/sources_1/bd/PWM/PWM_ooc.xdc
