# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Project/Wireless Charge PWM/PWM/PWM.srcs/sources_1/bd/PWM/ip/PWM_processing_system7_0_0/PWM_processing_system7_0_0.xci
# IP: The module: 'PWM_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/Wireless Charge PWM/PWM/PWM.gen/sources_1/bd/PWM/ip/PWM_processing_system7_0_0/PWM_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PWM_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Project/Wireless Charge PWM/PWM/PWM.srcs/sources_1/bd/PWM/ip/PWM_processing_system7_0_0/PWM_processing_system7_0_0.xci
# IP: The module: 'PWM_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/Wireless Charge PWM/PWM/PWM.gen/sources_1/bd/PWM/ip/PWM_processing_system7_0_0/PWM_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PWM_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
