# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Project/Wireless Charge PWM/PWM/PWM.srcs/sources_1/bd/PWM/ip/PWM_rst_ps7_0_200M_1/PWM_rst_ps7_0_200M_1.xci
# IP: The module: 'PWM_rst_ps7_0_200M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/Wireless Charge PWM/PWM/PWM.gen/sources_1/bd/PWM/ip/PWM_rst_ps7_0_200M_1/PWM_rst_ps7_0_200M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PWM_rst_ps7_0_200M_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Project/Wireless Charge PWM/PWM/PWM.gen/sources_1/bd/PWM/ip/PWM_rst_ps7_0_200M_1/PWM_rst_ps7_0_200M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'PWM_rst_ps7_0_200M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Project/Wireless Charge PWM/PWM/PWM.gen/sources_1/bd/PWM/ip/PWM_rst_ps7_0_200M_1/PWM_rst_ps7_0_200M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PWM_rst_ps7_0_200M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Project/Wireless Charge PWM/PWM/PWM.srcs/sources_1/bd/PWM/ip/PWM_rst_ps7_0_200M_1/PWM_rst_ps7_0_200M_1.xci
# IP: The module: 'PWM_rst_ps7_0_200M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/Wireless Charge PWM/PWM/PWM.gen/sources_1/bd/PWM/ip/PWM_rst_ps7_0_200M_1/PWM_rst_ps7_0_200M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PWM_rst_ps7_0_200M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Project/Wireless Charge PWM/PWM/PWM.gen/sources_1/bd/PWM/ip/PWM_rst_ps7_0_200M_1/PWM_rst_ps7_0_200M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'PWM_rst_ps7_0_200M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Project/Wireless Charge PWM/PWM/PWM.gen/sources_1/bd/PWM/ip/PWM_rst_ps7_0_200M_1/PWM_rst_ps7_0_200M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PWM_rst_ps7_0_200M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
