set_property IOSTANDARD LVCMOS33 [get_ports {PWM[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWM[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWM[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWM[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports EN_K]
set_property PACKAGE_PIN T14 [get_ports {PWM[3]}]
set_property PACKAGE_PIN T15 [get_ports {PWM[1]}]
set_property PACKAGE_PIN V16 [get_ports {PWM[2]}]
set_property PACKAGE_PIN W16 [get_ports {PWM[0]}]
set_property PACKAGE_PIN L14 [get_ports EN_K]
set_property IOSTANDARD LVCMOS33 [get_ports EN_LED]

set_property IOSTANDARD LVCMOS33 [get_ports {RST_LED[0]}]
set_property PACKAGE_PIN L15 [get_ports {RST_LED[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports RST_LED]
set_property PACKAGE_PIN N16 [get_ports RST]
set_property PACKAGE_PIN J16 [get_ports RST_LED]
set_property PACKAGE_PIN H15 [get_ports EN_LED]
